def notifyLINE(status) {
    withCredentials([string(credentialsId: 'line-notify-token-14', variable: 'TOKEN')]) { 
       def token = TOKEN
       def jobName = env.JOB_NAME
       def buildNo = env.BUILD_NUMBER
       
       def url = 'https://notify-api.line.me/api/notify'
       def message = "${jobName} Build #${buildNo} ${status} \r\n"
       sh "curl ${url} -H 'Authorization: Bearer ${token}' -F 'message=${message}'"
    }
}

pipeline {
    agent any
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                dir('./front-end'){
                    sh 'yarn install'
                }
            }
        }
        stage('Run unit test and Generate unit test report') {
            steps {
                dir('./front-end') {
                    sh 'yarn run jest:unit:cov'
                    
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage/lcov-report",
                        reportFiles: "index.html",
                        reportName: 'Unit Test Coverage Report'
                    ]

                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage",
                        reportFiles: "report.html",
                        reportName: 'Unit Test Report'
                    ]
                }
            }
        }
        stage('Run component test and Generate component test report') {
            steps {
                dir('./front-end'){
                    sh 'yarn run jest:component:cov'
        
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: './coverage/lcov-report',
                        reportFiles: 'index.html',
                        reportName: 'Component Test Coverage Report'
                    ]

                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage",
                        reportFiles: "report.html",
                        reportName: 'Component Test Report'
                    ]
                }
            }
        }
        stage('ฺBuild') {
            steps {
                script {
                        echo "Step: build"
                        // sh "docker-compose -f ./docker-compose-build.yaml build front_end"
                }
            }
        }
        stage('Push') {
            steps {
                script {
                        echo "Step: push"
                        // sh "docker-compose -f ./docker-compose-build.yaml push front_end"
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    echo "Step: Deploy"
                        // sshagent(credentials: ['team14-backend-server']) {
                        //     sh '''
                        //         [ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
                        //         ssh-keyscan -H 159.223.45.216 >> ~/.ssh/known_hosts
                        //         ssh root@159.223.45.216 'cd ./backend-14/ && docker-compose -f ./docker-compose-deploy.yaml pull && docker-compose -f ./docker-compose-deploy.yaml up -d'
                        //     '''
                    // }
                }
            }
        }
        stage('Run E2E test and Generate E2E test report') {
            steps {
                dir('./front-end'){
                    sh 'mkdir -p ./.nyc_output'
                    sh 'yarn cover:e2e'
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: './coverage/lcov-report',
                        reportFiles: 'index.html',
                        reportName: 'E2E Test Coverage Report'
                    ]
                }
            }
        }
    }
    post{
        success{
            notifyLINE("succeed")
        }
        failure{
            notifyLINE("failure")
        }
    }
}