def notifyLINE(status) {
    withCredentials([string(credentialsId: 'line-notify-token-14', variable: 'TOKEN')]) { 
       def token = TOKEN
       def jobName = env.JOB_NAME
       def buildNo = env.BUILD_NUMBER
       
       def url = 'https://notify-api.line.me/api/notify'
       def message = "${jobName} Build #${buildNo} ${status} \r\n"
       sh "curl ${url} -H 'Authorization: Bearer ${token}' -F 'message=${message}'"
    }
}

pipeline {
    agent any
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                dir('./back-end'){
                    sh 'yarn install'
                }
            }
        }
        stage('Run unit test and Generate unit test report') {
            steps {
                dir('./back-end') {
                    sh 'yarn run test:cov'
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: './coverage/lcov-report',
                        reportFiles: 'index.html',
                        reportName: 'Unit Test Coverage Report'
                    ]
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage",
                        reportFiles: "report.html",
                        reportName: 'Unit Test Report'
                    ]
                }
            }
        }
        stage('Run component test and Generate component test report') {
            steps {
                dir('./back-end') {
                    sh 'yarn run test:component:cov'
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: './coverage/lcov-report',
                        reportFiles: 'index.html',
                        reportName: 'Component Test Coverage Report'
                    ]
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage",
                        reportFiles: "report.html",
                        reportName: 'Component Test Report'
                    ]
                }
            }
        }
        stage('Build and Deploy') {
            steps {
                script {
                    // withCredentials([sshUserPrivateKey(credentialsId: 'team14-backend-server', keyFileVariable: 'identity', passphraseVariable: '', usernameVariable: 'userName')]) {
                    //     def remote = [:]
                    //     remote.name = "team-14-backend"
                    //     remote.host = "159.223.45.216"
                    //     remote.user = userName
                    //     remote.identityFile = identity
                    //     remote.allowAnyHosts = true
                    //     sshCommand remote: remote, command: 'echo "Hwllo world"'    
                    // }
                    withCredentials([usernamePassword(credentialsId: 'team-14', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        def remote = [:]
                        remote.name = "team-14-backend"
                        remote.host = "159.223.45.216"
                        remote.user = "${USERNAME}"
                        remote.identityFile = "${PASSWORD}"
                        remote.allowAnyHosts = true
                        sshCommand remote: remote, command: "echo 'Hello Mr. ${USERNAME}'"    
                    }
                // withCredentials([usernamePassword(credentialsId: 'team-14', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')], [string(credentialsId: 'backend-server', variable: 'HOST')])
                // withCredentials([string(credentialsId: 'backend-server', variable: 'HOST')])
                // script{
                //     def remote = [:]
                //     remote.name = "team-14-backend"
                //     remote.host = "$HOST"
                //     remote.user = "$USERNAME"
                //     remote.password = "$PASSWORD"
                //     remote.allowAnyHosts = true
                //     sshCommand remote: remote, command: "git clone -b main https://github.com/pspapleng/Project-SW-dev-tool-env-14.git team-14-backend"
                //     sshCommand remote: remote, command: "docker-compose -f team-14-backend/docker-compose-build.yaml build back_end"
                //     sshCommand remote: remote, command: "docker-compose -f team-14-backend/docker-compose-deploy.yaml up -d back_end"
                //     sshCommand remote: remote, command: "rm -r team-14-backend"
                //     sshCommand remote: remote, command: "docker rmi \$(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'psppx/team-14-backend') || true"
                // }     
                }     
            }
        }         
        stage('Test Backend') {
            steps {
                sh "curl http://159.223.45.216:4141/"
            }
        }
        stage('Run E2E test and Generate E2E test report') {
            steps {
                dir('./back-end') {
                    sh 'yarn run test:e2e:cov'
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: './coverage/lcov-report',
                        reportFiles: 'index.html',
                        reportName: 'E2E Test Coverage Report'
                    ]
                     publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage",
                        reportFiles: "report.html",
                        reportName: 'E2E Test Report'
                    ]
                }
            }
        }
    }
    post {
        success {
            notifyLINE("succeed")
        }
        failure {
            notifyLINE("failure")
        }
    }
}